cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - cache/

stages:
  - build
  - test
  - deploy

variables:
  NUGETDIR: ~/.nuget/NuGet
  NUGETPATH: ~/.nuget/NuGet/NuGet.Config

  APP_PATH: ./AftershipAPI
  TEST_PATH: ./AftershipAPITests
  PROD_NUGET: http://nuget.prod.aws.ajw-aviation.com/api/v2/Package

before_script:
  - mkdir -p ${NUGETDIR}
  - curl https://src.europe.ajw/configuration/NuGet/raw/master/NuGet.Config -o ${NUGETPATH} --insecure
  - cat $NUGETPATH
  - cp ${NUGETPATH} .
  - dotnet restore
  - curl https://src.europe.ajw/configuration/NuGet/raw/master/pushsource -o ~/pushsource --insecure
  - curl https://src.europe.ajw/configuration/NuGet/raw/master/pushkey -o ~/pushkey --insecure

dotnet_build:
  stage: build
  image: microsoft/dotnet:2.2-sdk
  script:
    - dotnet build ${APP_PATH}.sln
  tags:
    - docker

dotnet_test:
  stage: test
  image: microsoft/dotnet:2.2-sdk
  script:
    - dotnet test ${TEST_PATH}/${TEST_PATH}.csproj /p:CollectCoverage=true /p:CoverletOutput='TestResults/result.json'
  artifacts:
    paths:
      - ${TEST_PATH}/TestResults/
  tags:
    - docker
  dependencies:
  - dotnet_build

pages:
  stage: deploy
  dependencies:
    - dotnet_test
  script:
    - mv ${TEST_PATH}/TestResults/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

push_nuget_pre_release:
  only:
    - master
  stage: deploy
  image: microsoft/dotnet:2.2-sdk
  script:
    - export ts=$(date +"%y%m%d%H%M")
    - export pushsource=`cat ~/pushsource`
    - export pushkey=`cat ~/pushkey`
    - echo "Time was found to be $ts"
    - rm -f ${APP_PATH}/bin/Release/*.nupkg
    - dotnet pack ${APP_PATH}/${APP_PATH}.csproj /p:PackageVersion=1.0.0.$ts-beta --configuration Release
    - for f in ${APP_PATH}/bin/Release/*.nupkg; do dotnet nuget push $f --source $pushsource -k $pushkey; done
  environment:
    name: production
  tags:
    - docker
  dependencies:
    - dotnet_test


push_nuget:
  only:
    - master
  stage: deploy
  when: manual
  image: microsoft/dotnet:2.2-sdk
  script:
    - export ts=$(date +"%y%m%d%H%M")
    - export pushsource=`cat ~/pushsource`
    - export pushkey=`cat ~/pushkey`
    - echo "Time was found to be $ts"
    - rm -f ${APP_PATH}/bin/Release/*.nupkg
    - dotnet pack ${APP_PATH}/${APP_PATH}.csproj /p:PackageVersion=1.0.0.$ts --configuration Release
    - for f in ${APP_PATH}/bin/Release/*.nupkg; do dotnet nuget push $f --source $pushsource -k $pushkey; done
  environment:
    name: production
  tags:
    - docker
  dependencies:
    - dotnet_test
