language: csharp
dist: xenial
mono: none
dotnet: 2.2
install:
- dotnet restore
script:
- echo you the man now dog
# - dotnet test
after_success:
- echo dotnet test succeeded
after_failure:
- echo dotnet test failed
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY
  on:
    branch: master