
language: csharp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

# addons:
#   sonarcloud:
#     organization: "ajwgroup"
#     token:
#       secure: $SONARCLOUD_TOKEN

branches:
  only:
  - master
  - develop
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
dotnet: 2.2
mono: none
script:
  - chmod +x ./build.sh && ./build.sh --currentBranch=$TRAVIS_BRANCH --projectName=$PROJECT_NAME --verbose
  # - sonar-scanner