language: csharp
dist: xenial
mono: none
dotnet: 2.2
install:
- dotnet restore
script:
- dotnet test
after_success:
- echo dotnet test succeeded
after_failure:
- echo dotnet test failed
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: ./AftershipAPI/_site
    keep-history: true
on:
  branch: master