language: csharp
dotnet: 2.2
mono: none
dist: xenial

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

script:
  - dotnet build
  - dotnet test -c Release --no-build tests/AftershipAPITests/AftershipAPITests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_success:
  - echo dotnet test succeeded
after_failure:
  - echo dotnet test failed
after_script:
  - bash <(curl -s https://codecov.io/bash)