language: csharp
dotnet: 2.2
mono: none
dist: xenial

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
    - DOTNET_CLI_TELEMETRY_OPTOUT=1

addons:
  sonarcloud:
    organization: "ajwgroup"
    token:
      secure: $SONARCLOUD_TOKEN

script:
  - dotnet build AftershipAPI.sln -c Release
  - dotnet test -c Release --no-build tests/AftershipAPITests/AftershipAPITests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_success:
  - echo dotnet test succeeded
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner
after_failure:
  - echo There has been an issue with build/test

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY
  on:
    branch: master
